export const etudiantsARisque = [
  {
    id: 1,
    nom: 'Ndiaye',
    prenom: 'Amadou',
    matricule: 'SN123456',
    age: 22,
    faculte: 'Facultés des Sciences Juridiques et Politiques (FSJP)',
    sigleFaculte: 'FSJP',
    departement: 'Droit Public et Science Politique',
    sigleDepartement: 'DPSP',
    niveauEtude: 'Licence 3',
    pourcentageRisque: 75,
    notes: {
      moyenneGenerale: 8.2,
      moyenneSemestreActuel: 6.1,
      absences: 15,
    },
    assiduite: 78,
    situationFinanciere: 'Difficile',
    engagementsExtraCurriculaires: [
      'Membre du club de débat',
      "Bénévole à l'association X",
    ],
  },
  {
    id: 2,
    nom: 'Kameni',
    prenom: 'Marie',
    matricule: 'CM654321',
    age: 21,
    faculte: 'Faculté des Sciences (FS)',
    sigleFaculte: 'FS',
    departement: 'Physique (PH)',
    sigleDepartement: 'PH',
    niveauEtude: 'Licence 2',
    pourcentageRisque: 68,
    notes: {
      moyenneGenerale: 9.4,
      moyenneSemestreActuel: 8.7,
      absences: 8,
    },
    assiduite: 85,
    situationFinanciere: 'Moyenne',
    engagementsExtraCurriculaires: [
      "Membre de l'équipe de football",
      'Participe à des concours scientifiques',
    ],
  },
  {
    id: 3,
    nom: 'Mbou',
    prenom: 'David',
    matricule: 'TG987654',
    age: 23,
    faculte: 'Faculté des Sciences (FS)',
    sigleFaculte: 'FS',
    departement: 'Sciences Biomédicales (SBM)',
    sigleDepartement: 'SBM',
    niveauEtude: 'Master 1',
    pourcentageRisque: 52,
    notes: {
      moyenneGenerale: 10.1,
      moyenneSemestreActuel: 9.6,
      absences: 5,
    },
    assiduite: 92,
    situationFinanciere: 'Aisée',
    engagementsExtraCurriculaires: [
      "Président du club d'échecs",
      "Bénévole à l'hôpital",
    ],
  },
  {
    id: 4,
    nom: 'Fouda',
    prenom: 'Nadine',
    matricule: 'CM789012',
    age: 20,
    faculte: 'Faculté des Lettres et Sciences Humaines (FLSH)',
    sigleFaculte: 'FLSH',
    departement: 'Sociologie',
    sigleDepartement: 'SOC',
    niveauEtude: 'Licence 1',
    pourcentageRisque: 70,
    notes: {
      moyenneGenerale: 7.8,
      moyenneSemestreActuel: 6.5,
      absences: 12,
    },
    assiduite: 80,
    situationFinanciere: 'Difficile',
    engagementsExtraCurriculaires: ["Membre de l'association de sociologie"],
  },
  {
    id: 5,
    nom: 'Ngassa',
    prenom: 'Bertrand',
    matricule: 'CM345678',
    age: 22,
    faculte: 'Faculté des Sciences Economiques et de Gestion (FSEG)',
    sigleFaculte: 'FSEG',
    departement: 'Gestion',
    sigleDepartement: 'GES',
    niveauEtude: 'Licence 3',
    pourcentageRisque: 65,
    notes: {
      moyenneGenerale: 8.5,
      moyenneSemestreActuel: 7.2,
      absences: 10,
    },
    assiduite: 83,
    situationFinanciere: 'Moyenne',
    engagementsExtraCurriculaires: ["Trésorier du club d'entrepreneuriat"],
  },
  {
    id: 6,
    nom: 'Ewane',
    prenom: 'Celine',
    matricule: 'CM456789',
    age: 21,
    faculte: 'Faculté de Médecine (FM)',
    sigleFaculte: 'FM',
    departement: 'Médecine Générale',
    sigleDepartement: 'MG',
    niveauEtude: 'Licence 2',
    pourcentageRisque: 62,
    notes: {
      moyenneGenerale: 9.0,
      moyenneSemestreActuel: 8.0,
      absences: 7,
    },
    assiduite: 88,
    situationFinanciere: 'Aisée',
    engagementsExtraCurriculaires: ['Bénévole à la clinique universitaire'],
  },
  {
    id: 7,
    nom: 'Njambe',
    prenom: 'Emmanuel',
    matricule: 'CM567890',
    age: 23,
    faculte: 'Faculté des Sciences ',
    sigleFaculte: 'FS',
    departement: 'Informatique',
    sigleDepartement: 'INF',
    niveauEtude: 'Master 1',
    pourcentageRisque: 58,
    notes: {
      moyenneGenerale: 9.8,
      moyenneSemestreActuel: 8.9,
      absences: 9,
    },
    assiduite: 90,
    situationFinanciere: 'Moyenne',
    engagementsExtraCurriculaires: ['Développeur bénévole pour une ONG'],
  },
  {
    id: 8,
    nom: 'Ndoumbé',
    prenom: 'Aminata',
    matricule: 'CM678901',
    age: 22,
    faculte: 'Faculté des Sciences Juridiques et Politiques (FSJP)',
    sigleFaculte: 'FSJP',
    departement: 'Droit Privé',
    sigleDepartement: 'DP',
    niveauEtude: 'Licence 3',
    pourcentageRisque: 74,
    notes: {
      moyenneGenerale: 7.5,
      moyenneSemestreActuel: 6.3,
      absences: 14,
    },
    assiduite: 76,
    situationFinanciere: 'Difficile',
    engagementsExtraCurriculaires: [
      "Membre de l'association des étudiants en droit",
    ],
  },
  {
    id: 9,
    nom: 'Abena',
    prenom: 'Ousmane',
    matricule: 'CM789123',
    age: 21,
    faculte: 'Faculté des Sciences (FS)',
    sigleFaculte: 'FS',
    departement: 'Chimie',
    sigleDepartement: 'CHI',
    niveauEtude: 'Licence 2',
    pourcentageRisque: 67,
    notes: {
      moyenneGenerale: 8.7,
      moyenneSemestreActuel: 7.9,
      absences: 11,
    },
    assiduite: 82,
    situationFinanciere: 'Moyenne',
    engagementsExtraCurriculaires: ['Membre du club de chimie'],
  },
  {
    id: 10,
    nom: 'Essomba',
    prenom: 'Mariama',
    matricule: 'CM890123',
    age: 22,
    faculte: 'Faculté des Sciences ',
    sigleFaculte: 'FS',
    departement: 'Biologie',
    sigleDepartement: 'BIO',
    niveauEtude: 'Licence 3',
    pourcentageRisque: 60,
    notes: {
      moyenneGenerale: 9.5,
      moyenneSemestreActuel: 8.2,
      absences: 6,
    },
    assiduite: 89,
    situationFinanciere: 'Moyenne',
    engagementsExtraCurriculaires: ['Assistante de laboratoire'],
  },
  {
    id: 11,
    nom: 'Mve',
    prenom: 'Binta',
    matricule: 'CM901234',
    age: 23,
    faculte: 'Faculté des Lettres et Sciences Humaines (FLSH)',
    sigleFaculte: 'FLSH',
    departement: 'Littérature',
    sigleDepartement: 'LIT',
    niveauEtude: 'Master 1',
    pourcentageRisque: 55,
    notes: {
      moyenneGenerale: 9.9,
      moyenneSemestreActuel: 9.0,
      absences: 4,
    },
    assiduite: 91,
    situationFinanciere: 'Aisée',
    engagementsExtraCurriculaires: ['Rédactrice pour le journal universitaire'],
  },
  {
    id: 12,
    nom: 'Atangana',
    prenom: 'Saliou',
    matricule: 'CM012345',
    age: 24,
    faculte: 'Faculté des Sciences (FS)',
    sigleFaculte: 'FS',
    departement: 'Mathématiques',
    sigleDepartement: 'MATH',
    niveauEtude: 'Master 2',
    pourcentageRisque: 59,
    notes: {
      moyenneGenerale: 9.2,
      moyenneSemestreActuel: 8.5,
      absences: 5,
    },
    assiduite: 90,
    situationFinanciere: 'Moyenne',
    engagementsExtraCurriculaires: ['Tuteur en mathématiques'],
  },
  //... (le reste des étudiants)
];
